driver = "mysql"

output = "./app/models/entity"
pkgname = "models"
wipe = true
no-tests = true
add-enum-types = true

[mysql]
dbname = "guruchanDB"
user = "root"
pass = "root1234"
host = "localhost"
port = 3306
sslmode = "false"


tables = ["User", "Tag", "Food"]