// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	GFood string
	GTag  string
	GUser string
}{
	GFood: "g_food",
	GTag:  "g_tag",
	GUser: "g_user",
}
