// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("GFoods", testGFoodsUpsert)

	t.Run("GTags", testGTagsUpsert)

	t.Run("GUsers", testGUsersUpsert)
}
